name: Crypto Feed Scraper

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run even if recent articles exist'
        required: false
        default: false
        type: boolean

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm install
          npm install --workspace=@crypto-feed/scraper
      
      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          ENABLE_CURATION: ${{ secrets.ENABLE_CURATION || 'true' }}
          CURATION_BATCH_DELAY: ${{ secrets.CURATION_BATCH_DELAY || '200' }}
          NODE_ENV: production
        run: |
          cd packages/scraper
          npm run once
        
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-logs-${{ github.run_number }}
          path: packages/scraper/logs/
          retention-days: 7
      
      - name: Notify on success
        if: success()
        run: echo "✅ Scraper completed successfully at $(date)"
      
      - name: Notify on failure  
        if: failure()
        run: echo "❌ Scraper failed at $(date)"